### ISSUE TITLE
database Script.

### ISSUE THREAD

**Issue by asopiah** [Sam-Shudukhi/Bisenda#1]
Hi, 
Could you kindly provide the database script?

**Comment by halshudukhi** [comment]
Hi,
I uploaded it as a pdf file. Hope it helps.
You can find it here
https://github.com/Sam-Shudukhi/Bisenda/blob/master/Bisenda%20database.pdf

Thank you

**Comment by asopiah** [comment]
Would you please mind uploading .sql script ?

**Comment by halshudukhi** [comment]
Hello asopiah,
Yes, here you go
https://github.com/Sam-Shudukhi/Bisenda/blob/master/localhost.sql
